print("Hermione:  \tThat's totally barbaric!  \nRon:  \t\tThat's wizard's chess.")

class Piece:
    type = "empty"
    color ="blank"

class ChessBoard:
    a1 = Piece()
    a1.type = "Rook"
    a1.color = "White"
#    a2 = Piece()
#    a3 = Piece()
#    a5 = Piece()
#    a6 = Piece()
#    a7 = Piece()
#    a8 = Piece()
#    b1 = Piece()
#    b2 = Piece()
#    b3 = Piece()
#    b4 = Piece()
#    b5 = Piece()
#    b6 = Piece()
#    b8 = Piece()
#    b7 = Piece()
#    c1 = Piece()
#    c2 = Piece()
#    c3 = Piece()
#    c4 = Piece()
#    c5 = Piece()
#    c6 = Piece()
#    c7 = Piece()
#    d2 = Piece()
#    c8 = Piece()
#    d3 = Piece()
#    d4 = Piece()
#    d5 = Piece()
#    d6 = Piece()
#    d8 = Piece()
#    e1 = Piece()
#    e2 = Piece()
#    e4 = Piece()
#    e5 = Piece()
#    e6 = Piece()
#    e7 = Piece()
#    e8 = Piece()
#    f1 = Piece()
#    f2 = Piece()
#    f3 = Piece()
#    f4 = Piece()
#    f5 = Piece()
#    f6 = Piece()
#    f7 = Piece()
#    f8 = Piece()
#    g1 = Piece()
#    g2 = Piece()
#    g3 = Piece()
#    g4 = Piece()
#    g5 = Piece()
#    g6 = Piece()
#    g7 = Piece()
#    g8 = Piece()
#    h1 = Piece()
#    h2 = Piece()
#    h3 = Piece()
#    h4 = Piece()
#    h5 = Piece()
#    h6 = Piece()
#    h7 = Piece()
#    h8 = Piece()

theBoard = ChessBoard()

print(theBoard.a1)
print(theBoard.a1.color)
print(theBoard.a1.type)
